### ISSUE TITLE
Admin function not working on Windows installations.

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#142]
Item | Description
-----|-------------
**File(s):** | `admin/index.php`, `admin/base_roleadmin.php` & `admin/base_useradmin.php`
**Class:** | N/A
**Function:** | N/A
**Similar Issues:** | #94 
**Depends on Issue(s):** | #144 & #145
**Dependency Type:** | Hard
**Misc. Info.:** | •The website has a programming error.
---
**Expected Behavior:** Admin pages display on Windows installations.
**Current Behavior:** App crashes when trying to load admin pages on windows installations.

**Comment by NathanGibbs3** [comment]
Information from the web server's error log may be helpful in diagnosing this issue.
Thanks. :smile:

**Comment by mesteele** [comment]
I have attached the Apache2 error log file.
[error.log](https://github.com/NathanGibbs3/BASE/files/10669309/error.log)

**Comment by NathanGibbs3** [comment]
Trey pulling down the latest commit from the [devel](https://github.com/NathanGibbs3/BASE/tree/devel) branch, see if that fixes it. :smile:

**Comment by mesteele** [comment]
I can now get to the Administration page. I can create a user and that is all. If I try to List Users, List Roles or Create a Role it jumps back to the base_main.php page.

Attached is the log file.
[error.log](https://github.com/NathanGibbs3/BASE/files/10670740/error.log)

**Comment by NathanGibbs3** [comment]
Is `$Use_Auth_System` set to `1` in your `base_conf.php` file?

**Comment by mesteele** [comment]
No it is not set but when I do set it to 1 going into BASE it jumps right to base_denied.php and displays:

The website cannot display the page HTTP 500 
     
Most likely causes:
•The website is under maintenance.
•The website has a programming error.
 
Attached log file.
[error.log](https://github.com/NathanGibbs3/BASE/files/10675708/error.log)

**Comment by NathanGibbs3** [comment]
> I can now get to the Administration page. I can create a user and that is all. If I try to List Users, List Roles or Create a Role it jumps back to the base_main.php page.
> 
That is by design, with the Authentication system off, creating users is the only function that can be performed.
The idea is to:
1. Allow creation of admin user(s).
2. Enable the Auth system in `base_conf.php` by setting Is `$Use_Auth_System` to 1.
3. Log in as an admin user.
4. Finish setting up users & roles from there.

The admin menus displayed when the Auth system is disabled do not make that obvious. Opened Issue #144 to address that.

**Comment by NathanGibbs3** [comment]
Try the latest commit from the [devel](https://github.com/NathanGibbs3/BASE/tree/devel) branch.
Lets see if something sensible comes up when your Auth System is turned on. :smile:

**Comment by mesteele** [comment]
When I set $Use_Auth_System to 1 I can no longer get to the Administration page. I believe there should be a logon screen displayed when $Use_Auth_System is set to 1?

I can create a user/s when $Use_Auth_System is set to 0 but I'm unable to list them. It does create them because I duplicate the user and BASE tells me the user already exists.

I believe in PHP5 of BASE I can do all the option in Administration with $Use_Auth_System set to 0, which is default. I don't have PHP5 version running right now, but will work on it.

**Comment by NathanGibbs3** [comment]
> When I set $Use_Auth_System to 1 I can no longer get to the Administration page. I believe there should be a logon screen displayed when $Use_Auth_System is set to 1?
> 
With `$Use_Auth_System` set to 1
Accessing index.php should give you the login page.
Accessing `base_main.php` should redirect you to `base_denied.php` which should provide a clickable link to `index.php`.
Admin functions should be fully operational.

With `$Use_Auth_System` set to 0
Accessing index.php should should redirect you to `base_main.php`
Accessing `base_main.php` should work as expected.
Admin functions should be limited to create user.

> I can create a user/s when $Use_Auth_System is set to 0 but I'm unable to list them. It does create them because I duplicate the user and BASE tells me the user already exists.
> 

Correct, that limitation was added in commit 432d21942513b4c304dde064c9a1d14160213324.
This was done to limit potentially sensitive information disclosure when the Auth System was disabled.

> I believe in PHP5 of BASE I can do all the option in Administration with $Use_Auth_System set to 0, which is default. I don't have PHP5 version running right now, but will work on it.

Correct, the original BASE 1.4.5 and earlier versions released by @secureideas, et al, had this information disclosure issue.

Also, thank you so much for including the error logs when things don't work.
They are giving an idea of what is happening on your end, which helps us find and address issues. 
Issues #143 & #145 came straight out of your error logs.

**Comment by mesteele** [comment]
There are no admin functions unless an Admin user is created and the $Use_Auth_System is set to 1 and you are logged in. They all work as long as you are logged in as Admin. The links for the admin fails if you are not setup with an admin account and when the link fails is gets an error on the base_denied.php page.
[error.log](https://github.com/NathanGibbs3/BASE/files/10680996/error.log)

**Comment by NathanGibbs3** [comment]
> There are no admin functions unless an Admin user is created and the $Use_Auth_System is set to 1 and you are logged in. They all work as long as you are logged in as Admin. 

Correct, the only function that should work when the Auth System is off is user creation.

> The links for the admin fails if you are not setup with an admin account 

Correct. I am currently working on code to not display those choices to the end user under these conditions, as it is quite confusing, when clicking the links for them don't do anything. Issue #144 Thank you for bringing this to my attention. :smile:

> and when the link fails is gets an error on the base_denied.php page. [error.log](https://github.com/NathanGibbs3/BASE/files/10680996/error.log)

And, this is what should **not** be happening to the end user. #145 

Are you running the latest `base_denied.php` from the [devel](https://github.com/NathanGibbs3/BASE/tree/devel) branch? 
I believe that I fixed the `base_denied.php` not loading issue in the last commit to [devel](https://github.com/NathanGibbs3/BASE/tree/devel).
From the line numbers in the last error.log, it appears that you are running an older version of `base_denied.php`.

**Comment by mesteele** [comment]
I just installed the latest and it is fixed. Thanks :)

Another access issue when $Use_Auth_System set to 0 uses are allowed to do certian function in the Cashe &

**Comment by NathanGibbs3** [comment]
> I just installed the latest and it is fixed. Thanks :)
> 
> Another access issue when $Use_Auth_System set to 0 uses are allowed to do certain function in the Cache & Status page that maybe they shouldn't?

Good find, I'll definitely look into that. :smile:
Thank you so much for your help. All of the Unit testing in the world would not have necessarily found what this issue and subsequent discussion has brought to light.
Again, Thank You. :smile:
Your contributions to this project have been noted in the [Wiki](https://github.com/NathanGibbs3/BASE/wiki/Contributor-Recognition)
