### ISSUE TITLE
Information & destructive operations exposed to unauthenticated users.

### ISSUE THREAD

**Issue by NathanGibbs3** [NathanGibbs3/BASE#146]
Item | Description
-----|-------------
**File(s):** | `base_maintenance.php ` & `includes/base_log_error.inc.php`
**Class:** | N/A
**Function:** | `includes/base_log_error.inc.php`-`PrintPageHeader()`
**Related Issue(s):** | #89 #142 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | TMI & TMF exposed to unauthenticated or non-admin users. Thank you @mesteele
---
**Expected Behavior:** Less info and **NO** functionality should be exposed.
**Current Behavior:** A lot of info and functionality is exposed.

**Comment by mesteele** [comment]
Development-Latest: Being logged in using $Use_Auth_System = 1;

If all users are deleted, it gets an error:

The specified CGI application misbehaved by not returning a complete set of HTTP headers. The headers it did return are "PHP Notice: Unauthorized user access: michael in D:\winids\inetpub\wwwroot\base\includes\base_auth.inc.php on line 563 Attempt Redirect Status: 302 Found X-Powered-By: PHP/7.4.33 Expires: Thu, 19 Nov 1981 08:52:00 GMT Cache-Control: no-store, no-cache, must-revalidate Pragma: no-cache Location: http://winids/base_main.php Content-type: text/html; charset=UTF-8 ".

Not real sure what needs to be done but not allowing the logged in account to be deleted could be the solution?

**Comment by NathanGibbs3** [comment]
Opened Issue #156 to track this. Please continue conversation on that Issue's ticket. Thank you for finding this. :smile:
