### ISSUE TITLE
Deleting logged in user crashes app.

### ISSUE THREAD

**Issue by NathanGibbs3** [NathanGibbs3/BASE#156]
Item | Description
-----|-------------
**File(s):** | `admin/base_useradmin.php`
**Class:** | 
**Function:** | 
**Similar Issues:** | #146 
**Depends on Issue(s):** | #190 
**Dependency Type:** | Hard
**Misc. Info.:** | Development-Latest: Being logged in using `$Use_Auth_System = 1`; If the logged in user credentials are deleted BASE gets an error: `The specified CGI application misbehaved by not returning a complete set of HTTP headers. The headers it did return are "PHP Notice: Unauthorized user access: michael in D:\winids\inetpub\wwwroot\base\includes\base_auth.inc.php on line 563 Attempt Redirect Status: 302 Found X-Powered-By: PHP/7.4.33 Expires: Thu, 19 Nov 1981 08:52:00 GMT Cache-Control: no-store, no-cache, must-revalidate Pragma: no-cache Location: http://winids/base_main.php Content-type: text/html; charset=UTF-8 "`. Not real sure what needs to be done maybe any logged in users should not be able to be deleted until they are logged out?
---
**Expected Behavior:** App logs user out and deletes the user.
**Current Behavior:** App deletes the user without logging them out first.

**Comment by NathanGibbs3** [comment]
Hey @mesteele, I finally have a chance to look at this.

This should only be possible when `$Use_Auth_System = 1`, and
This should only be possible if the logged in user is an admin user..
Only an admin user should be able to do this as all other users should be locked out of user admin functions.
Basically, a user who could delete their own account would have to be an admin user.
Is that what you have on your end, an admin user deleting their own account from the list users page?

The flow of the app on deleting a user is to delete the user then reload the list users page.
If the logged in user's account has been deleted, the list users page throws an `Unauthorized user access:` error with the user name, then redirects to the main base page.
The main base page then throw an `Unauthorized user access:` error with the user name, then redirects to the base denied page.
This is exactly what happens on my end, and is exactly what should happen..

From the output that you provided it looks like the error notices are going to standard output on your system and messing up the redirects.

This appears to be a server software misconfiguration on your system, that is allowing PHP errors to go to standard output.
Check out this or other PHP error handling settings on your system.
https://www.php.net/manual/en/errorfunc.configuration.php#ini.display-errors

**Comment by NathanGibbs3** [comment]
Can you verify that this is still an Issue?
I'm guessing that fixing #190 on your installation probably cleared this up as well.

Suggestion, if you are going to test this by deleting a logged in admin account, have a backup admin account enabled so that you don't lock yourself out of BASE.

I know from experience, on my end, disabling or deleting the admin account that I'm logged in under kicks me out of BASE, I end up on the base denied page, unable to log back in as admin.
Had to turn off the auth system, create a new admin account, re-enable auth system, log in as new admin, re-enable or recreate old admin account. :-)

**Comment by mesteele** [comment]
If I delete the account that I'm logged in as, it jumps to the login prompt, and I can login as another user.
IIS Log:
[php_errors.log](https://github.com/NathanGibbs3/BASE/files/11408507/php_errors.log)

**Comment by NathanGibbs3** [comment]
Excellent, we are no longer getting a crash, BASE is doing what it should.. This one is done.
