### ISSUE TITLE
Base allows unauthenticated users access to Alert Group Maintenance functions

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#161]
Item | Description
-----|-----
**File(s):** | `base_auth.inc.php` & `base_ag_main.php`
**Class:** | 
**Function:** | `AuthorizedPage()`
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | There was also a side issue affecting `AuthorizedPage()` on windows systems, that would contribute to this.
---
**Expected Behavior: Redirected to login notification
**Current Behavior: All functions are available

**Comment by NathanGibbs3** [comment]
Just tested on my installation.
Putting the URL of the Alert Group Maintenance page into the browser without authenticating to BASE first, simply redirected to the base denied page. This is exactly what should happen..

As with Issue #156, I have no idea why it is not working on your system.

**Comment by NathanGibbs3** [comment]
Question, are the header and footer menu's showing up on the BASE login page on your installation?

**Comment by mesteele** [comment]
I'm not having that issue. The issues I'm having is related to the database under 8.x. There are a lot of the links that are having database issues.
BASE FATAL ERROR:
BASE DB NULL Recordset Database ERROR: Column 'ip_proto' in field list is ambiguous

I have team viewer setup, and this is a test site. I have barnyard2 shut off but there are a lot of alerts in the database.

ID: 1 734 085 311
PW: znu43q2t

There are a couple of other issues:
1) Users that are not authorized can create groups.
2) When I go to the Archive database it does not show anything under Traffic Profile by Protocol. Once an alert has been added it does show up.

**Comment by NathanGibbs3** [comment]
Team Viewer?
Absolutely not.
https://www.zdnet.com/article/following-oldsmar-attack-fbi-warns-about-using-teamviewer-and-windows-7/

**Comment by mesteele** [comment]
It is a temporary OS that gets deleted, but I understand.

There are three issues that I'm dealing with, but there could be more under PHP8.

1) I'm using the archive database function. If there are no events all the protocols are missing leaving the screen blank where they normally are. If I add one event to the archive database all the protocols show up. If I delete the one event the protocols disappear. 
![2023-04-07_21-02-21](https://user-images.githubusercontent.com/12111398/230696947-1f17230d-9aa6-4cb9-9e32-6850957d08d6.png)

2) If I have $Use_Auth_System = 0; I can still get in and do all the functions in the Alert Group Maintenance.
![2023-04-07_21-04-13](https://user-images.githubusercontent.com/12111398/230697053-b6ea5822-045a-40e0-8954-68b621c301c3.png)

3) I'm getting a lot of broken links that give these:
- Last Source Ports:  **All three links fail**
BASE FATAL ERROR
BASE DB NULL Recordset Database ERROR: Column 'ip_src' in field list is ambiguous. 
 - Last Destination Ports: **All three links fail**
BASE FATAL ERROR:
BASE DB NULL Recordset Database ERROR: Column 'ip_proto' in field list is ambiguous
![2023-04-07_21-06-52](https://user-images.githubusercontent.com/12111398/230697089-d33424c7-2077-483a-8ef8-38cb92e176f3.png)
- Most recent 15 Alerts: **All four links work**

All the rest of the links get errors associated with the table they belong to.

**Comment by NathanGibbs3** [comment]
OK, I see what you are saying.

If the Auth system is off, I don't see any issues with allowing users to mess with the alert groups.
If the Auth system is on, the create,edit,and delete functions should be locked out for users with in roles below ag_editor, possibly even the clear function.
