### ISSUE TITLE
Make the graphing & email functions optional based on the availablity of the required PEAR packages.

### ISSUE THREAD

**Issue by NathanGibbs3** [NathanGibbs3/BASE#180]
Item | Description
-----|-------------
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | #92 
**Dependency Type:** | Hard
**Misc. Info.:** | This allows BASE to function without requiring installation of the `Mail`, `Mail_Mime`, & `Image_Graph` PEAR packages. With the PEAR packages installed, BASE has graphing & email functions, but now could run without them.
---
**Expected Behavior:** BASE runs with functions dependent on PEAR packages disabled when PEAR packages are not installed.
**Current Behavior:** BASE crashes if PEAR packages are not installed.

**Comment by mesteele** [comment]
To disable graphing and have the options ghosted out, just remove the Pear packages?

It would be handy to be able to turn the function off at any time without having to remove any packages.

```
/ * This option is used to disable the Graphing function
  * 0 : no
  * 1 : yes
*/
$use_graphing = 0;
```
