### ISSUE TITLE
Event Time Stamp is Wrong

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#184]
Item | Description
-----|-------------
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** The timestamps for the events are wrong.
My PHP.INI is : date.timezone = America/New_York
![2023-04-21_22-04-56](https://user-images.githubusercontent.com/12111398/233756419-aabdbc08-38d4-4cd8-a843-75dbb1b6d377.png)

 
---
**Expected Behavior:** 
**Current Behavior:**

**Comment by mesteele** [comment]
This might be an issue on my side. Looking at the snort logs and the transfer from Barnyard2 to the database. My log files in Short are odd. Deleting the entire logs and letting it restart.

**Comment by mesteele** [comment]
This was an error on my side.

**Comment by NathanGibbs3** [comment]
No problem, and thanks. 😄
