### ISSUE TITLE
PHP 7 Auth = 1 causes error.

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#191]
Item | Description PHP 7 causes an error when trying to authenticate.
-----|-------------
**File(s):** | `includes/base_rtl.php`
**Class:** | 
**Function:** | `GetPHPSV()`
**PHP Version**: | 7.3+
**PHPUnit Version**: | 
**Composer Version**: | 
**ADODB Version**: | 
**Similar Issues:** | 
**Depends on Issue(s):** | #193 
**Dependency Type:** | Hard
**Misc Info**: | RTL v 0.0.1+ Change the return type of GetPHPSV() to return array.
---
**Expected Behavior**: 
App runs.
**Current Behavior**:
App crashes on PHP 7.3+
**Solution**:

IIS Log:
[php_errors.log](https://github.com/NathanGibbs3/BASE/files/11409716/php_errors.log)

**Comment by NathanGibbs3** [comment]
Exactly which PHP version?
The line referenced in the error should not execute on PHP below 7.2

**Comment by NathanGibbs3** [comment]
I also see you are running Kernel 0.0.1, pull the latest from devel that has 0.0.2.
That commit knows about issue #190, so the cookie path will be set correctly on installations where `$BASE_urlpath` is set to an empty string. I think that is what is causing this.
If the latest commit from devel does the same thing, then we have a real bug, otherwise, it's #190 all over again.

**Comment by mesteele** [comment]
I have a few PHP 5.6.40 installs running Kevin's last release. I haven't tried the latest development on PHP 5. Should it work on PHP 5?

The above problem was caused when running a previous commit on PHP 7.

My test systems are PHP 7.4.33 and PHP 8.2.5

Should I be exclusively using the latest devl on PHP 7 and PHP 8?

**Comment by NathanGibbs3** [comment]
I try to keep BASE backwards compatible with older PHP,s.
What parts of BASE I have built unit tests for get tested on travis-ci from PHP 5.2 - 8-1.
It, should work on older versions..

**Comment by NathanGibbs3** [comment]
> I have a few PHP 5.6.40 installs running Kevin's last release. I haven't tried the latest development on PHP 5. Should it work on PHP 5?
> 
> The above problem was caused when running a previous commit on PHP 7.
> 
OK, sounds like it's fixed then. :smile:

**Comment by mesteele** [comment]
PHP apparently has two active versions being developed (8.1.xx and 8.2.xx).

I am using PHP 8.2.5 to test on, so should I move back to 8.1.xx so as not to leapfrog over the version you are using?

>> I try to keep BASE backwards compatible with older PHP,s.

**Comment by NathanGibbs3** [comment]
> > I have a few PHP 5.6.40 installs running Kevin's last release. I haven't tried the latest development on PHP 5. Should it work on PHP 5?
> > The above problem was caused when running a previous commit on PHP 7.
> 
> OK, sounds like it's fixed then. 😄

This one just bit me, looks like I'm wrong about this one.
It's alive and valid.
