### ISSUE TITLE
Non-operable buttons in Cache and Status.

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#194]
Item | Description It appears that all the buttons in Cache and Status are not operating. Only tested on MySQL 5/7/8 with same result. The screen only blanks. Attached is the Apache log and the PHP log. No errors are produced from either Apache or PHP. Not sure if this is a misconfiguration on my end but BASE 1.4.5 under PHP 5 has no issues.
-----|-------------
**File(s):** | `base_maintenance.php `
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | Developer Error ID10T. 🤦 
---
**Expected Behavior:** 
**Current Behavior:**
![2023-05-08_13-29-17](https://user-images.githubusercontent.com/12111398/236897239-c9bbcbe6-ca8a-441d-a74a-862f1147bf6a.png)
[Apache error.log](https://github.com/NathanGibbs3/BASE/files/11423808/Apache.error.log)
[php_errors.log](https://github.com/NathanGibbs3/BASE/files/11423809/php_errors.log)

**Comment by NathanGibbs3** [comment]
That's not cool, kind of defeats the purpose of admin functions. 😮 
I'm guessing when we fixed #146 we broke something.

**Comment by NathanGibbs3** [comment]
![20230508_210423.jpg](https://user-images.githubusercontent.com/9939563/236968577-eeb4f704-ef94-4c38-8513-0b19c9c7748f.jpg)

The smoking gun. 🤦‍♂️

**Comment by mesteele** [comment]
That fixed that part :)

**Comment by NathanGibbs3** [comment]
Root cause analysis, not enough ☕ in developer's blood stream. LOL!
