### ISSUE TITLE
Unable to Delete events or Move/Copy events to the Archive database.

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#195]
Item | Description Placing a check mark in the event does nothing when I select to Delete it (one or more), Move it (one or more) or Copy it (one or more) to the archive database. It appears that the error on the screen is pointing to two possible causes. The screen shot shows the error and you can replace the copy with move and delete as the same error pops up for each failed process. I included the error logs but neither Apache nor PHP throws an error.  The PHP log shows the loading of the base_conf everytime I preform a function? 
-----|-------------
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | 
---
**Expected Behavior:** 
**Current Behavior:**
![2023-05-09_9-35-14](https://github.com/NathanGibbs3/BASE/assets/12111398/582a91ce-b528-4677-aa8d-a4a
[php_errors.log](https://github.com/NathanGibbs3/BASE/files/11431823/php_errors.log)
098301713)
[error.log](https://github.com/NathanGibbs3/BASE/files/11431824/error.log)

**Comment by NathanGibbs3** [comment]
I see it too, I definitely broke something, again.

> The PHP log shows the loading of the base_conf everytime I preform a function?

The stateless nature of the HTTP protocol. Every request is a new request.
