### ISSUE TITLE
Deleting events will cause a time out issue

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#196]
Item | Description Deleting a lot of events will cause an Internal Server Error. I know there is a FastCGI configuration setting to extend the time out function but is there a possibility that when this happens it jumps back to BASE instead of the Server error page? This error may also happen when clearing the database in the Admin function? 
-----|-------------
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** |
- [x] Build BASE Server Error landing page.
---
**Expected Behavior:** 
BASE specific custom error page is displayed.
**Current Behavior:**
![2023-05-11_15-53-47](https://github.com/NathanGibbs3/BASE/assets/12111398/e696fdcc-4361-428f-b5b4-d2
[php_errors.log](https://github.com/NathanGibbs3/BASE/files/11456149/php_errors.log)
364fd3b4a0)
[error.log](https://github.com/NathanGibbs3/BASE/files/11456150/error.log)

**Comment by NathanGibbs3** [comment]
This is more a server specific issue than a BASE issue.
When the server, Apache / IIS / whatever, decides that BASE has been running too long it kills the process, hence the timeout and / or the server error page.

A terminated BASE process has no ability to influence what the server does next.
Unless we are running BASE of the living dead, zombie apocalypse edition, in which case the BASE process will reanimate and send the user to an appropriate page. Probably https://youtu.be/8tmzjaN2DWc 🤣 

The `$max_script_runtime` setting in `base_conf.php` can be increased.
The default installation value is 180 seconds..
If BASE hasn't finished the request in 3 minutes, probably something is wrong.

As we know, legacy BASE code is known to be notoriously inefficient, for instance #174, in that case BASE was sequentially walking through every event in the DB, to generate a set of forward & back buttons. 🤯 
Limiting the DB query to the three events necessary to generate the buttons sped this up exponentially. 😄 

If you are routinely dealing with large amounts of alerts, increasing this may help, as it gives BASE a longer stay of execution, but once the server kills the BASE process, it is dead.

**Comment by NathanGibbs3** [comment]
Quick question, does the server throw an HTTP status code on these timeouts?
If it does, custom error pages may be the solution.
Getting them working would be a server specific configuration process, but providing a page in the BASE source that the server could send to the user when this happens isn't a bad idea.

Once the BASE process is killed by the server, the responsibility of serving up a provided error page is on the web server itself, failure to do so would be a web server misconfiguration issue, not a BASE issue.

**Comment by mesteele** [comment]
This is on Apache2:

Selecting a lot of events to delete.
![2023-05-24_15-26-29](https://github.com/NathanGibbs3/BASE/assets/12111398/9d9b6f6a-7e5b-4f7d-8b93-979a41ac5572)

Apache Log: [error.log](https://github.com/NathanGibbs3/BASE/files/11558270/error.log)

PHP Log: [php_errors.log](https://github.com/NathanGibbs3/BASE/files/11558273/php_errors.log)

**Comment by mesteele** [comment]
The custom error pages have worked. Not the best but for the interim, but works :)

**Comment by NathanGibbs3** [comment]
It hasn't been pushed to devel yet, but a BASE specific server error landing page has been built.
It should just be a matter of configuring the web server to use it as opposed to it's standard error page.

**Comment by mesteele** [comment]
I see it has been pushed to the devl but I'm not sure how to utilize the BASE specific server error landing page in either Apache or IIS?

**Comment by mesteele** [comment]
Seems to work :)
![2023-05-29_14-35-35](https://github.com/NathanGibbs3/BASE/assets/12111398/bd787f98-73e8-4e8d-b302-77a2ef2211f3)

**Comment by NathanGibbs3** [comment]
Once the BASE process is killed by the server, the responsibility of serving up a provided error page is on the web server itself, failure to do so would be a web server configuration issue, not a BASE issue.
Examples of how to get this working for specific web servers wold be welcome additions to the BASE documentation.

However, to be clear, we are now out of BASE land and into web server specific configuration land.
Suggestion, submit a bug report to the web server software.

**Comment by mesteele** [comment]
Yes, I figured as there was no actual error thrown. Lots of issues on the web about the same thing happening. BASE just hangs there with the progress indicator spinning making it appear that it is still processing but the process has actually stopped.
 
When IIS throws an Error 500 if has a detailed reason explaining exactly why it was thrown.

I'll work on it and post the resolution, if I can find one for IIS :)
