### ISSUE TITLE
IE 7x display issue vertical multicolored lines.

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#199]
Item | Description: Most recent 15 Unique Alerts and Most frequent 5 Unique Alerts are showing vertical-colored lines where they shouldn't. I have attached pictures. Both options do show the correct number of alerts.
-----|-------------
**File(s):** | ` base_stat_*.php`
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | #140 
**Dependency Type:** | Hard
**Misc. Info.:** | Affects IE 7x. Issue #140 again.
---
**Expected Behavior:** 
**Current Behavior:**
Most recent 15 Unique Alerts:
![15](https://github.com/NathanGibbs3/BASE/assets/12111398/cadc0df5-b783-4cc6-b0da-d2dab0160556)
Most frequent 5 Unique Alerts:
![5](https://github.com/NathanGibbs3/BASE/assets/12111398/124223a1-ec1d-4bb5-9bff-2f0f0ab2b879)

**Comment by mesteele** [comment]
It appears it does the above on all the links in the picture below.
![2023-05-12_21-31-30](https://github.com/NathanGibbs3/BASE/assets/12111398/d9514b80-c0ca-46c8-a5c7-8c4f74edb581)

**Comment by NathanGibbs3** [comment]
Unable to reproduce this one.
Will need more info.
Apache or IIS?
PHP 7 or 8?

**Comment by mesteele** [comment]
I went ahead and downloaded the latest development, just to make sure. I just tested it on IIS and Apache with same result.

PHP 8.2.5
ADOdb 5.22.5
With all the graphing installed.

**Comment by NathanGibbs3** [comment]
Thank you, now that is actionable data. :smile:
I'll load it up in IE and see what I can find.

**Comment by NathanGibbs3** [comment]
Can we get a browser version on that?
@mesteele

**Comment by NathanGibbs3** [comment]
> I found issue. I have been testing on Internet Explorer and when I switch to either Edge or Firefox the issue goes away. It is a compatibility issue with IE. I'm not sure when the issue showed up but BASE 1.4.5 does not have that issue.
> 
> With **IE**, when I click on "- Most recent 15 Alerts: any protocol" it does display correctly, so it might be a simple link issue that could keep IE compatible.

Could you look through the links table on the main page and figure out which php files are behind this?

We already know `base_stat_alerts.php` is on the list.

**Comment by mesteele** [comment]
IE: 11.1790.17763.0

I think you got all the links. The space between the **Displaying alerts 1-xx of xxxx total** and the top of the fame below it changes from link to link. I think there is supposed to be one line feed between.

**Comment by NathanGibbs3** [comment]
I'm only getting this when putting IE into IE7 compatibility mode.
Putting it into compatibility modes for 5, 8, 9, & 10 doesn't do this, so it's an IE 7x issue.
As `base_qry_main.php` runs OK, we need to figure out why the other pages don't.
They all call the same code.

**Comment by mesteele** [comment]
I'm using IE 11, so maybe that is it?

**Comment by mesteele** [comment]
I'm using IE 11, so maybe that is it?

If you turn off colored alerts off, the issue goes away. It appears to create one colored line per event posted when **- Most recent 15 Unique Alerts** it creates 15 lines of color.

**Comment by NathanGibbs3** [comment]
I turned off colored alerts earlier too, what I got was alternating gray & white lines.

**Comment by NathanGibbs3** [comment]
It's #140

**Comment by mesteele** [comment]
Looks like you have it under control. I didn't see this under BASE 1.4.5 and PHP5.

**Comment by NathanGibbs3** [comment]
That was a good find.
Probably, no one is running IE7, but if they are, we will have this fixed shortly.

**Comment by mesteele** [comment]
I have IE 11 and the issue of the lines was on that. It all looks good now :)

**Comment by NathanGibbs3** [comment]
![Screenshot 2023-05-14 11 51 20](https://github.com/NathanGibbs3/BASE/assets/9939563/1e9d0daf-8b76-4a74-94d7-951781c5160d)
At the end of the day, the original BASE code was generating invalid HTML, which was the cause of this.
