### ISSUE TITLE
Graph Alert Detection Time header ghosted

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#202]
Item | Description The header for Graph Alert Detection Time is ghosted
-----|-------------
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | 
---
**Expected Behavior:** 
**Current Behavior:**
![2023-05-20_12-59-00](https://github.com/NathanGibbs3/BASE/assets/12111398/d68c1136-9223-4ec8-bbba-1deeefc7d609)

**Comment by NathanGibbs3** [comment]
Damn it Roman!
Style Info in HTML.
![Screenshot 2023-05-20 14 05 01](https://github.com/NathanGibbs3/BASE/assets/9939563/c5afc7be-694a-4895-808b-454a3aa2363b)
Damn it Kevin!
`styles/base_*style.css`
![Screenshot 2023-05-20 14 06 22](https://github.com/NathanGibbs3/BASE/assets/9939563/0474c0e2-0ff5-40d3-ac1e-a0809aae6000)

**Comment by NathanGibbs3** [comment]
Those two keep us busy, that's for sure. :smile:
