### ISSUE TITLE
Kill switch for graphing

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#209]
Item | Description
-----|-------------Can a configuration be added to the BASE configuration file that will disable all the graphing on demand. Including removing the on-screen links when it is disabled.
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | #180 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | 
---
**Expected Behavior:** 
**Current Behavior:**

**Comment by NathanGibbs3** [comment]
Already there. #180
