### ISSUE TITLE
GEO IP ip2cc file executable check fails on Windows.

### ISSUE THREAD

**Issue by mesteele** [NathanGibbs3/BASE#210]
Item | Description Trying to setup the below and it gives an error that file is not found or executable. It is in the folder. There is no .pl extension and I did add it but no luck

```
/** 2. Second method for the mapping of ip addresses to country names:
 * 
 * If you have installed the perl module IP::Country
 * http://search.cpan.org/dist/IP-Country/
 * (requires Geography::Countries as well),
 * then uncomment and correct the absolute path to this perl executable:
 */
 $IP2CC = "d:\winids\php\ip2cc";
```
----|-------------
**File(s):** | 
**Class:** | 
**Function:** | 
**Similar Issues:** | 
**Depends on Issue(s):** | 
**Dependency Type:** | 
**Misc. Info.:** | 
---
**Expected Behavior:** 
**Current Behavior:**

**Comment by NathanGibbs3** [comment]
Definitely a Windows specific issue.

This is from the PHP manual.
https://www.php.net/manual/en/function.is-executable
> Note: On Windows, a file is considered executable, if it is a properly executable file as reported by the Win API GetBinaryType(); for BC reasons, files with a .bat or .cmd extension are also considered executable. Prior to PHP 7.4.0, any non-empty file with a .exe or .com extension was considered executable. Note that PATHEXT is irrelevant for is_executable(). 

So changing the `ip2cc` file extension to `cmd`, `bat`, ( and/ or `exe`, or `com` on PHP < 7.4x ) might make it work.

I'm not even sure how `ip2cc` would get off the ground from the Windows CLI as it uses the Unix shebang syntax to bootstrap the Perl interpreter. `#!/usr/bin/perl`.
I'm guessing that the windows Perl implementation takes care of that somehow.
