### ISSUE TITLE
tr bgcolor="#" if prio not in $priority_colors (unknown event class)

### ISSUE THREAD

**Issue by FalcoGer** [NathanGibbs3/BASE#57]
When colors are enabled in the base_config.php and an unknown event is to be displayed, $priority_colors is accessed by an invalid index resuilting in a
```html
<tr bgcolor="#">
```
which in turn results in a black background, making the line unreadable.
I am not very well versed in php, but i managed to apply a local fox in includes/base_output_query.inc.php

```php
function qroPrintEntryHeader($prio=1, $color=0) {
 global $priority_colors;
 if($color == 1) {
   if (array_key_exists($prio, $priority_colors)) {
     echo '<TR BGCOLOR="#'.$priority_colors[$prio].'">';
   } else {
     echo '<TR BGCOLOR="#DDDDDD">';
   }
 } else {
   echo '<TR BGCOLOR="#'.((($prio % 2) == 0) ? "DDDDDD" : "FFFFFF").'">';
 }
}
```

**Comment by NathanGibbs3** [comment]
# Thanks @FalcoGer . :smile:
- [ ] Could you find out what the value of `$prio` is when `qroPrintEntryHeader` is called with an unknown event.
- [ ] An excerpt from you web server error log when this occurs would also be helpful.

# TO DO List for @NathanGibbs3 :
- [ ] Build Unit Test for function `qroPrintEntryHeader`.
- [ ] Duplicate bug on our end.
- [ ] Fix this issue #57.
- [ ] Modify Unit Test appropriately.
- [ ] Push fix to GitHub. :smile:

**Comment by FalcoGer** [comment]
My apologies. I read this way too late and the logs are gone now.
I believe there was no reference to a class, the query returning NULL at this point. So $prio was either NULL or 0. But I really can't remember.
But the logs said something about an invalid array access at this $priority_colors[$prio].

**Comment by NathanGibbs3** [comment]
Verified that a `$prio` value that is not a valid index of array `$priority_colors` or of NULL will trigger this bug when the color parameter for `qroPrintEntryHeader`  is set.
Some input validation will definitely be needed here. :smile:

**Comment by NathanGibbs3** [comment]
Also triggered if global variable `$priority_colors` is not defined. Opened Issue #59

**Comment by NathanGibbs3** [comment]
Issue #60 was found while working on this. :smile:
